"""add avatar

Revision ID: 65b07a271956
Revises: 5a14a5dc28bf
Create Date: 2026-03-18 10:49:23.665749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b07a271956'
down_revision: Union[str, Sequence[str], None] = '5a14a5dc28bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_receiver_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_uid'), table_name='messages')
    op.drop_table('messages')
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receiver_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_sender_uid'), 'messages', ['sender_uid'], unique=False)
    op.create_index(op.f('ix_messages_receiver_uid'), 'messages', ['receiver_uid'], unique=False)
    # ### end Alembic commands ###
