"""add chat_enabled

Revision ID: dc4f64377f1e
Revises: 65b07a271956
Create Date: 2026-03-24 11:38:49.310131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc4f64377f1e'
down_revision: Union[str, Sequence[str], None] = '65b07a271956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hackMate_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_uid', sa.String(), nullable=True),
    sa.Column('user2_uid', sa.String(), nullable=True),
    sa.Column('chat_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackMate_matches_id'), 'hackMate_matches', ['id'], unique=False)
    op.create_table('hackmate_swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swiper_uid', sa.String(), nullable=True),
    sa.Column('swiped_uid', sa.String(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hackmate_swipes_id'), 'hackmate_swipes', ['id'], unique=False)
    op.create_index(op.f('ix_hackmate_swipes_swiped_uid'), 'hackmate_swipes', ['swiped_uid'], unique=False)
    op.create_index(op.f('ix_hackmate_swipes_swiper_uid'), 'hackmate_swipes', ['swiper_uid'], unique=False)
    op.create_table('hackmate_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_index(op.f('ix_hackmate_users_id'), 'hackmate_users', ['id'], unique=False)
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_messages_receiver_uid'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_uid'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_swipes_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_swiped_uid'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_swiper_uid'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('firebase_uid', name=op.f('users_firebase_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('swipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('swiper_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('swiped_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('swipes_pkey'))
    )
    op.create_index(op.f('ix_swipes_swiper_uid'), 'swipes', ['swiper_uid'], unique=False)
    op.create_index(op.f('ix_swipes_swiped_uid'), 'swipes', ['swiped_uid'], unique=False)
    op.create_index(op.f('ix_swipes_id'), 'swipes', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('receiver_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_sender_uid'), 'messages', ['sender_uid'], unique=False)
    op.create_index(op.f('ix_messages_receiver_uid'), 'messages', ['receiver_uid'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user1_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user2_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('matches_pkey'))
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.drop_index(op.f('ix_hackmate_users_id'), table_name='hackmate_users')
    op.drop_table('hackmate_users')
    op.drop_index(op.f('ix_hackmate_swipes_swiper_uid'), table_name='hackmate_swipes')
    op.drop_index(op.f('ix_hackmate_swipes_swiped_uid'), table_name='hackmate_swipes')
    op.drop_index(op.f('ix_hackmate_swipes_id'), table_name='hackmate_swipes')
    op.drop_table('hackmate_swipes')
    op.drop_index(op.f('ix_hackMate_matches_id'), table_name='hackMate_matches')
    op.drop_table('hackMate_matches')
    # ### end Alembic commands ###
